apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentportfolio
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: studentportfolio
  template:
    metadata:
      labels:
        app: studentportfolio
    spec:
      containers:
        - name: studentportfolio
          image: ghcr.io/lsy010101/devops-m6-studentportfolio:8e338b4c10ec6a378ebf37f27e639a718cc90aa7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: studentportfolio-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: studentportfolio-html
          configMap:
            name: studentportfolio-html
