apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
        - name: transactions
          image: ghcr.io/lsy010101/devops-m6-transactions:8e338b4c10ec6a378ebf37f27e639a718cc90aa7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017
            - name: PORT
              value: "3000"
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 8
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 25
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
